export type MethodType = 'GET' | 'POST' | 'PUT' | 'DELETE';
export type sortListType = {
  title: string;
  options: any;
};
// Generated by https://quicktype.io

export interface TransactionResponseProps {
  data: Transaction[];
  success: number;
  httpStatus: string;
  message: string;
}

export interface Transaction {
  id: string;
  amount: number;
  issuer_id: string;
  receiver_id: null;
  status: string;
  sense: string;
  issuer_account: string;
  receiver_account: string;
  customer_account: string;
  service: string;
}


export interface IUser {
  id: string;
  username: string;
  displayName: string | null;
  email: string;
  passwordHash: string;
  avatarUrl: string | null;
  bio: string | null;
  phoneNumber: string;
  role: string;
  createdAt: string;
}

export interface IOrganisation {
  id: string;
  createdAt: string;
  updatedAt: string;
  type: string;
  name: string;
  email: string;
  telephone: string;
  longitude: string;
  latitude: string;
  address: string;
  openHours: string;
  closingHours: string;
  description: string;
  userId: string;
  user: IUser;
}

export interface IDrug {
  id: string;
  name: string;
  description: string;
  quantity: number;
  price: number;
  createdAt: string;
  updatedAt: string;
  organisationId: string;
  userId: string;
  organisation: IOrganisation;
}

export type SiteRole =
  | "ADMIN"
  | "USER"
  | "PHARMACIST"
  | "ALL"
