import type { Metadata } from 'next';
import { Barlow } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'src/components/layout/themes/theme-provider';
import StoreProvider from 'src/redux/StoreProvider';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import { cn } from 'src/lib/utils';
import { Toaster } from 'src/components/ui/toaster';

const barlow = Barlow({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Pharmacy App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>      
      <body className={barlow.className}>
       
          <StoreProvider>
            <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange>
              {children}
              <Toaster />
            </ThemeProvider>
          </StoreProvider>
      </body>
    </html>
  );
}
